### ISSUE TITLE
Latest InvokeAI?

### ISSUE THREAD

**Issue by neymue** [ai-dock/invokeai#2]
I really appreciate this docker, super easy to use with runpod. However, I'm wondering how would I get the latest version of InvokeAI? I see the `AUTO_UPDATE` tag which supposedly pulls the latest in default, but my version is 4.2.5 instead of the latest version of InvokeAI which is 4.2.7. (they've added an upscaling module which is a much needed improvement) Are these images updated manually from your end? Or is there a way to get the latest version?

**Comment by robballantyne** [comment]
Currently the builds are done throughout GitHub actions, but they're started manually. I'm working on fixing that though the 'lastest' tag will always be a manually reviewed stable.

I'll build the new version today for you 

Auto updating needs fixing for this image, but I'll get to that asap

**Comment by robballantyne** [comment]
@neymue `ghcr.io/ai-dock/invokeai:v2-cuda-12.1.1-base-22.04-v4.2.7` is ready.  I'll point latest at it when I've had a chance to properly test it, but should be fine

**Comment by russjr08** [comment]
Any chance I could request a version bump on this again? Invoke just recently had a pretty major version update, and it'd be great to see it here.

Thanks for your hard work on getting this put together, its fantastic! ❤️

**Comment by gitwittidbit** [comment]
Is the invoke version fixed in the container? My impression was that it can update inside the container...

There is this docker env setting for INVOKE_VERSION. I bumped this in the docker compose to 5.1.1 and also put an argument in .env setting this to 5.1.1.

But Invoke does not update. It stays at 4.2.4.

Is that how it is supposed to be? If so, what is environment variable for?

Thanks!

**Comment by russjr08** [comment]
@gitwittidbit I was able to update InvokeAI in the container by making a few manual adjustments. Make sure you have `INVOKEAI_VERSION` set to `5.1.1` to the docker command (it can also just be hardcoded in the update script if you already have a container running). Then start a shell in the container (either via SSH, a Jupyter notebook terminal - this environment does include Jupyter by default which is nice!, or a `docker exec` command if you have access).

Then head over to `/opt/ai-dock/bin` in the shell and edit `update-invokeai.sh` with your favorite editor (either within the shell, or via an external editor):

- If you need to change the InvokeAI version variable after the docker container has already been launched, do so on line 5 (in my case, I have it set to `version="5.1.1"`). Then on the pip install command that it runs at the bottom, you'll need to update a few things:

```
$INVOKEAI_VENV_PIP install --no-cache-dir --use-pep517 \
  torch==2.4.1 \
  torchaudio \
  xformers \
  InvokeAI${version+==$version}
```

I've changed the `torch` variable because the container has a different version of PyTorch than what Invoke expects, and it will fail to install if its not updated. Then I've also forced it to reinstall `torchaudio` and `xformers` because those are tied to the version of PyTorch/`torch` that is installed (so if you only change the PyTorch version, things will still fail to start).

After those changes are saved, run the `update-invokeai.sh` script (`./update-invokeai.sh` if you're in the `/opt/ai-dock/bin` directory mentioned earlier). This process may take a while, depending on the hardware and connectivity speed of the host that you're running on.

I believe the reason why InvokeAI doesn't update at startup is due to the fact that Invoke will sometimes change/update their required PyTorch dependency, which isn't accounted for in the update script. Full disclosure, I'm not sure if any of the other functionality of the container is tied to that specific version of Torch (and therefor I do not know if anything will "break" as a result of changing it - such as Jupyter which I don't really have any experience with / utilize myself).

Lastly, I tested this on a clean install of InvokeAI - if you have anything important saved on your instance, be sure to take a backup copy of it since while I do believe the Invoke team tries to ensure upgrades go smoothly, backups never hurt anyone :)

Edit: Oops, almost forgot - you of course need to restart InvokeAI after you update it. Use either the process manager from the service portal to do this, or just run `sudo supervisorctl restart invokeai` from the shell - do not restart the docker container itself since this will just reset all of the changes and you'll need to make them again.

**Comment by robballantyne** [comment]
This is the way. There is nothing dependent on torch other than invoke so nothing should break. 

I'll try and push a new version tomorrow.
